call plug#begin('~/.vim/plugged')

" Catch common weasel words like 'easy' when writing prose in Markdown.
Plug 'nicholaides/words-to-avoid.vim'

" Make the quickfix window modifiable for large find and replace operations.
Plug 'stefandtw/quickfix-reflector.vim'

" Smart completion of do/end.
Plug 'tpope/vim-endwise'

" Convenience shortcuts for quickly navigating quicklists and such.
Plug 'tpope/vim-unimpaired'

" Make netrw more awesome.
Plug 'tpope/vim-vinegar'

" Fix Python autoindent after <CR> following parentheses.
Plug 'Vimjas/vim-python-pep8-indent'

" Integrate a test runner.
Plug 'vim-test/vim-test'

if has('nvim')
    let test#strategy = 'neovim'
endif

call plug#end()

" I don't really like folds. Disable them (some plugin is enabling by default
" on reStructured Text).
set nofoldenable

" Hide instead of close files when opening a new file while there are unsaved
" changes
set nohidden

" OS X does some weird stuff to PATH on zsh that messes with venvs.
" Using bash is a safe alternative and I don't really need the power
" of zsh through Vim.
set shell=/bin/bash

" Assume HTML files are Django templates for simplicity.
autocmd BufNewFile,BufRead *.html set filetype=htmldjango

" Handlebars syntax highlighting uses a Mustache plugin.
autocmd BufNewFile,BufRead *.hbs set filetype=mustache

" Run LuaFormatter on save.
autocmd BufWrite *.lua call LuaFormat()

" Use a different comment style for Django's HTML templates.
autocmd FileType htmldjango set commentstring={#\ %s\ #}

" Insert pdb.
nnoremap <Leader>d oimport pdb; pdb.set_trace()<Esc>

" Run a test file.
nmap <silent> <Leader>f :TestFile<CR>

" Run a test suite.
nmap <silent> <Leader>s :TestSuite<CR>

" Run a test.
nmap <silent> <Leader>t :TestNearest<CR>
