" Hide instead of close files when opening a new file while there are unsaved
" changes
set nohidden

" OS X does some weird stuff to PATH on zsh that messes with venvs.
" Using bash is a safe alternative and I don't really need the power
" of zsh through Vim.
set shell=/bin/bash

" Assume HTML files are Django templates for simplicity.
autocmd BufNewFile,BufRead *.html set filetype=htmldjango

" Run LuaFormatter on save.
autocmd BufWrite *.lua call LuaFormat()

" Use a different comment style for Django's HTML templates.
autocmd FileType htmldjango set commentstring={#\ %s\ #}

" Insert pdb.
nnoremap <Leader>d oimport pdb; pdb.set_trace()<Esc>

