-- -- Neovim LSP completion source
-- --
-- -- This plugin provides more completion capabilities
-- -- that the Neovim client can expose to LSP servers.
-- -- The LSP server can then enrich what the completion engine can do.
-- Plug "hrsh7th/cmp-nvim-lsp"
--
-- -- Neovim completion engine
-- --
-- -- This plugin is the core completion engine that can be fed completions
-- -- from sources like an LSP server or a snippet plugin.
-- Plug "hrsh7th/nvim-cmp"
--
-- -- Include other LSP sources
-- --
-- -- This plugin makes it possible to use external tools and treat them
-- -- as sources that will be plugged into the LSP ecosystem.
-- -- By using this in combination with Mason, I can add tools like Black
-- -- without installing a dedicated Black plugin.
-- Plug "jose-elias-alvarez/null-ls.nvim"
--
-- -- Snippet engine
-- --
-- -- This is tool for doing fancy autocomplete of common activities
-- -- (e.g., making a function with a standard docstring)
-- --
-- -- TODO: learn more about this later. For now, nvim-cmp requires a snippet
-- -- engine for some reason and that's the only reason why I've included
-- -- this plugin.
-- Plug "L3MON4D3/LuaSnip"
--
-- -- LuaSnip completion source connector
-- --
-- -- This plugin bridges the LuaSnip snippet engine
-- -- as a source for the Neovim completion engine.
-- Plug "saadparwaiz1/cmp_luasnip"
--
-- vim.call("plug#end")
-- Global configuration
--
-- Do this stuff before loading plugins so that plugins have a consistent behavior.
-- Set the leader key to spacebar.
--
-- This is, hands down, one of Vim's superpowers that is possible
-- because of modal editing.
vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.g.rg_command = "rg --vimgrep -S"

require("mblayman/options")
require("mblayman/keymaps")
require("mblayman/lazy_bootstrap")
require("mblayman/lazy_init")

-- FIXME: Replace with the new auto format plugin.
-- -- This autocommand group is for attaching a format on save option
-- -- to each buffer.
-- local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
--
-- --  This function gets run when an LSP connects to a particular buffer.
-- local on_attach = function(client, bufnr)
--
--
--   -- Create a command `:Format` local to the LSP buffer
--   vim.api.nvim_buf_create_user_command(bufnr, "Format",
--                                        function(_) vim.lsp.buf.format() end,
--                                        {desc = "Format current buffer with LSP"})
--
--   -- Enable format on write.
--   if client.supports_method("textDocument/formatting") then
--     vim.api.nvim_clear_autocmds({group = augroup, buffer = bufnr})
--     vim.api.nvim_create_autocmd("BufWritePre", {
--       group = augroup,
--       buffer = bufnr,
--       callback = function() vim.lsp.buf.format({bufnr = bufnr}) end,
--     })
--   end
-- end
--
-- -- Enable other tools that can be used by LSP
--
-- local null_ls = require("null-ls")
--
-- null_ls.setup({
--   sources = {
--     null_ls.builtins.formatting.lua_format, -- Lua
--     null_ls.builtins.formatting.black, -- Python
--     null_ls.builtins.formatting.isort, -- Python
--   },
--   on_attach = on_attach,
-- })
--
-- -- Completion engine (nvim-cmp)
-- --
-- -- To make use of all the cool LSP server stuff,
-- -- nvim-cmp needs to be configured to use the LSP as a source.
-- local cmp = require "cmp"
-- local luasnip = require "luasnip"
--
-- cmp.setup({
--   -- Tell nvim-cmp how to expand snippets.
--   snippet = {expand = function(args) luasnip.lsp_expand(args.body) end},
--   -- Set the key mappings for the completion engine to track.
--   mapping = cmp.mapping.preset.insert({
--     -- TODO: These mappings with Ctrl do not seem to be working.
--     ["<C-d>"] = cmp.mapping.scroll_docs(-4),
--     ["<C-f>"] = cmp.mapping.scroll_docs(4),
--     ["<C-Space>"] = cmp.mapping.complete(),
--     ["<CR>"] = cmp.mapping.confirm({
--       behavior = cmp.ConfirmBehavior.Replace,
--       select = false,
--     }),
--     ["<Tab>"] = cmp.mapping(function(fallback)
--       if cmp.visible() then
--         cmp.select_next_item()
--       elseif luasnip.expand_or_jumpable() then
--         luasnip.expand_or_jump()
--       else
--         fallback()
--       end
--     end, {"i", "s"}),
--     ["<S-Tab>"] = cmp.mapping(function(fallback)
--       if cmp.visible() then
--         cmp.select_prev_item()
--       elseif luasnip.jumpable(-1) then
--         luasnip.jump(-1)
--       else
--         fallback()
--       end
--     end, {"i", "s"}),
--   }),
--   -- Specify the completion sources.
--   sources = {{name = "nvim_lsp"}, {name = "luasnip"}},
-- })

-- For some reason, Neovim is not recognizing the templ file extension.
-- There is probably a better way to do this, but this is fine for now.
vim.cmd [[autocmd BufNewFile,BufRead *.templ set ft=templ]]
