export EDITOR=nvim
PATH="/usr/local/sbin:$PATH"
export PATH
WORKON_HOME="$HOME/.virtualenvs"
export WORKON_HOME
export MYPYPATH="$HOME/git/dod-backend/dod_backend"
export BAT_THEME="GitHub"
export GR_HOME="$HOME/git"
